In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
import keras
from keras.layers import Dense
from keras.models import Sequential
dataset = pd.read_csv('iris.csv',names=['sep_l','sep_w','pet_l','pet_w','label'])

In [2]:
dataset

sep_l  sep_w  pet_l  pet_w           label
0      5.1    3.5    1.4    0.2     Iris-setosa
1      4.9    3.0    1.4    0.2     Iris-setosa
2      4.7    3.2    1.3    0.2     Iris-setosa
3      4.6    3.1    1.5    0.2     Iris-setosa
4      5.0    3.6    1.4    0.2     Iris-setosa
..     ...    ...    ...    ...             ...
145    6.7    3.0    5.2    2.3  Iris-virginica
146    6.3    2.5    5.0    1.9  Iris-virginica
147    6.5    3.0    5.2    2.0  Iris-virginica
148    6.2    3.4    5.4    2.3  Iris-virginica
149    5.9    3.0    5.1    1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
X = dataset.iloc[:,0:4].values

In [4]:
y = dataset.iloc[:,[4]].values

In [5]:
y

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
ohe = OneHotEncoder(sparse=False)

In [8]:
y = ohe.fit_transform(y)

In [9]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [11]:
X_train.shape

(120, 4)

In [12]:
X_test.shape

(30, 4)

In [13]:
model = Sequential()
model.add(Dense(10,activation="relu",input_dim=4))
model.add(Dense(10,activation="relu"))
model.add(Dense(3,activation="softmax"))

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.compile(loss="categorical_crossentropy",optimizer='sgd',metrics=['accuracy'])

In [16]:
model.fit(X_train,y_train,epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 3ms/step - loss: 1.2771 - accuracy: 0.3333
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0996 - accuracy: 0.3000
Epoch 3/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0206 - accuracy: 0.3000
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9591 - accuracy: 0.3667
Epoch 5/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9387 - accuracy: 0.2667
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9187 - accuracy: 0.3000
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9389 - accuracy: 0.2833
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9045 - accuracy: 0.3000
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 0.8848 - accuracy: 0.3167
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 0.8758 - accuracy: 0.3750
Epoch 11/100
4/4 [===========

4/4 [==============================] - 0s 8ms/step - loss: 0.4143 - accuracy: 0.7917
Epoch 84/100
4/4 [==============================] - 0s 6ms/step - loss: 0.3886 - accuracy: 0.9083
Epoch 85/100
4/4 [==============================] - 0s 7ms/step - loss: 0.3839 - accuracy: 0.8417
Epoch 86/100
4/4 [==============================] - ETA: 0s - loss: 0.3753 - accuracy: 0.93 - 0s 6ms/step - loss: 0.3891 - accuracy: 0.8917
Epoch 87/100
4/4 [==============================] - 0s 7ms/step - loss: 0.4078 - accuracy: 0.8417
Epoch 88/100
4/4 [==============================] - 0s 6ms/step - loss: 0.3757 - accuracy: 0.9250
Epoch 89/100
4/4 [==============================] - 0s 5ms/step - loss: 0.3707 - accuracy: 0.9333
Epoch 90/100
4/4 [==============================] - 0s 7ms/step - loss: 0.3985 - accuracy: 0.8083
Epoch 91/100
4/4 [==============================] - 0s 3ms/step - loss: 0.3644 - accuracy: 0.9500
Epoch 92/100
4/4 [==============================] - 0s 6ms/step - loss: 0.3622 - accuracy

In [17]:
model.evaluate(X_test)

1/1 [==============================] - 0s 183ms/step - loss: 0.0000e+00 - accuracy: 0.0000e+00


[0.0, 0.0]

In [18]:
y_pred = model.predict(X_test)

In [19]:
y_pred.round()

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [20]:
y_test = np.argmax(y_test,axis=1)
y_pred = np.argmax(y_pred,axis=1)

In [21]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [22]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 2, 0, 2, 2, 0, 0, 2, 2,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [23]:
print(confusion_matrix(y_test,y_pred))

[[11  0  0]
 [ 0  7  6]
 [ 0  0  6]]


In [24]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.54      0.70        13
           2       0.50      1.00      0.67         6

    accuracy                           0.80        30
   macro avg       0.83      0.85      0.79        30
weighted avg       0.90      0.80      0.80        30

