In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
import keras
from keras.layers import Dense
from keras.models import Sequential

In [6]:
dataset = pd.read_csv('iris.csv',names=['sep_l','sep_w','pet_l','pet_w','label'])

In [7]:
dataset

sep_l  sep_w  pet_l  pet_w           label
0      5.1    3.5    1.4    0.2     Iris-setosa
1      4.9    3.0    1.4    0.2     Iris-setosa
2      4.7    3.2    1.3    0.2     Iris-setosa
3      4.6    3.1    1.5    0.2     Iris-setosa
4      5.0    3.6    1.4    0.2     Iris-setosa
..     ...    ...    ...    ...             ...
145    6.7    3.0    5.2    2.3  Iris-virginica
146    6.3    2.5    5.0    1.9  Iris-virginica
147    6.5    3.0    5.2    2.0  Iris-virginica
148    6.2    3.4    5.4    2.3  Iris-virginica
149    5.9    3.0    5.1    1.8  Iris-virginica

[150 rows x 5 columns]

In [8]:
X = dataset.iloc[:,0:4].values

In [9]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
y = dataset.iloc[:,4].values

In [11]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le = LabelEncoder()

In [14]:
y = le.fit_transform(y)

In [15]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [17]:
X_train.shape

(120, 4)

In [18]:
X_test.shape

(30, 4)

In [19]:
model = Sequential([
    Dense(10,activation="relu",input_shape=[4]),
    Dense(10,activation="relu"),
    Dense(3,activation="softmax")
])

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                50        
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.compile(loss="sparse_categorical_crossentropy",optimizer='sgd',metrics=['accuracy'])

In [27]:
model.fit(X_train,y_train,epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 7ms/step - loss: 1.4073 - accuracy: 0.2833
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 1.1100 - accuracy: 0.1833
Epoch 3/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0151 - accuracy: 0.2083
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9615 - accuracy: 0.3833
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9285 - accuracy: 0.5167
Epoch 6/100
4/4 [==============================] - 0s 5ms/step - loss: 0.9089 - accuracy: 0.5750
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 0.8815 - accuracy: 0.6167
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8676 - accuracy: 0.6333
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8612 - accuracy: 0.6833
Epoch 10/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8313 - accuracy: 0.6750
Epoch 11/100
4/4 [===========

4/4 [==============================] - 0s 2ms/step - loss: 0.3318 - accuracy: 0.9167
Epoch 85/100
4/4 [==============================] - 0s 2ms/step - loss: 0.3399 - accuracy: 0.9000
Epoch 86/100
4/4 [==============================] - 0s 3ms/step - loss: 0.3267 - accuracy: 0.9250
Epoch 87/100
4/4 [==============================] - 0s 3ms/step - loss: 0.3471 - accuracy: 0.9083
Epoch 88/100
4/4 [==============================] - 0s 3ms/step - loss: 0.3319 - accuracy: 0.9250
Epoch 89/100
4/4 [==============================] - 0s 3ms/step - loss: 0.3180 - accuracy: 0.9417
Epoch 90/100
4/4 [==============================] - 0s 3ms/step - loss: 0.3153 - accuracy: 0.9000
Epoch 91/100
4/4 [==============================] - 0s 3ms/step - loss: 0.3149 - accuracy: 0.9333
Epoch 92/100
4/4 [==============================] - 0s 3ms/step - loss: 0.3204 - accuracy: 0.9000
Epoch 93/100
4/4 [==============================] - 0s 3ms/step - loss: 0.3152 - accuracy: 0.9250
Epoch 94/100
4/4 [===============

In [28]:
model.evaluate(X_test,y_test)

1/1 [==============================] - 0s 235ms/step - loss: 0.3445 - accuracy: 0.8333


[0.34445828199386597, 0.8333333134651184]

In [29]:
y_pred = model.predict(X_test)

In [30]:
y_pred.round()

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [31]:
y_pred = np.argmax(y_pred,axis=1)

In [32]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 2, 1, 2, 0, 2, 2, 0, 0, 2, 2,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [33]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [36]:
print(confusion_matrix(y_test,y_pred))

[[11  0  0]
 [ 0  8  5]
 [ 0  0  6]]


In [38]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.62      0.76        13
           2       0.55      1.00      0.71         6

    accuracy                           0.83        30
   macro avg       0.85      0.87      0.82        30
weighted avg       0.91      0.83      0.84        30

